name: Testing

on:
  pull_request:
    branches:
      - master
jobs:
  dependencies:
      name: "dependencies"
      runs-on: "ubuntu-latest"

      steps:
        - name: "Checkout under $GITHUB_WORKSPACE"
          uses: "actions/checkout@master"

        - name: "Set up NodeJS"
          uses: "actions/setup-node@master"
          with:
            node-version: 16

        - name: "Install yarn"
          run: "npm install -g yarn"

        - name: "Install dependencies"
          run: "yarn install"

        - name: "Cache files"
          uses: "actions/cache@master"
          id: "main-files"
          with:
            path: "./*"
            key: "${{ github.sha }}"
  test-icon-components:
    name: Test icon components
    needs: dependencies
    if: ${{ success() }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@master

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: "Restore cache files"
        uses: "actions/cache@master"
        id: "main-files"
        with:
          path: "./*"
          key: "${{ github.sha }}"

      - name: Run Jest Tests
        run: yarn test:icons
  test-playground:
    name: Test playground
    needs: test-icon-components
    if: ${{ success() }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@master

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: "Restore cache files"
        uses: "actions/cache@master"
        id: "main-files"
        with:
          path: "./*"
          key: "${{ github.sha }}"

      - name: Run Jest Tests
        run: yarn test:playground
